version: "3.9"

services:
    btc-uah:
        container_name: btc_uah
        build: ./apps/btc-uah
        ports:
          - 3000:3000
        volumes:
          - emails:/app/
  
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq:/var/lib/rabbitmq

volumes:
    emails: {}
    rabbitmq: {}
