name: Node.js CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'
            - name: Install Eslint
              run: |
                  npm ci
            - name: Eslint working flow
              run: |
                  npm run eslint:check
            - name: Prettier working flow
              run: |
                  npm run format:check
            - name: Test
              run: |
                  npm test
